### ISSUE TITLE
Not install properly via python setup.py build and install

### ISSUE THREAD

**Issue by wheatdog** [infokiller/i3-workspace-groups#24]
It seems that this line is the problem
https://github.com/infokiller/i3-workspace-groups/blob/d765709fc1f4034d4cf56e9c03b6f1adc93553b8/setup.py#L31

I believe it should be
```
find_packages(exclude=["*.tests", "*.tests.*", "tests.*", "tests"])
```

**Comment by infokiller** [comment]
What error are you getting?

**Comment by wheatdog** [comment]
It seems only install following files,
```
/usr/
/usr/bin/
/usr/bin/i3-assign-workspace-to-group
/usr/bin/i3-autoname-workspaces
/usr/bin/i3-focus-on-workspace
/usr/bin/i3-move-to-workspace
/usr/bin/i3-rename-workspace
/usr/bin/i3-select-workspace-group
/usr/bin/i3-switch-active-workspace-group
/usr/bin/i3-workspace-groups
/usr/lib/
/usr/lib/python3.7/
/usr/lib/python3.7/site-packages/
/usr/lib/python3.7/site-packages/i3_workspace_groups-0.4.6a3-py3.7.egg-info/
/usr/lib/python3.7/site-packages/i3_workspace_groups-0.4.6a3-py3.7.egg-info/PKG-INFO
/usr/lib/python3.7/site-packages/i3_workspace_groups-0.4.6a3-py3.7.egg-info/SOURCES.txt
/usr/lib/python3.7/site-packages/i3_workspace_groups-0.4.6a3-py3.7.egg-info/dependency_links.txt
/usr/lib/python3.7/site-packages/i3_workspace_groups-0.4.6a3-py3.7.egg-info/requires.txt
/usr/lib/python3.7/site-packages/i3_workspace_groups-0.4.6a3-py3.7.egg-info/top_level.txt
```

and I got this if i run `i3-workspace-groups`

```
Traceback (most recent call last):
  File "/usr/bin/i3-workspace-groups", line 12, in <module>
    from i3wsgroups import cli
ModuleNotFoundError: No module named 'i3wsgroups'
```

**Comment by infokiller** [comment]
Sorry for the issue, now it should be fixed.

**Comment by orhun** [comment]
I'm getting the same error on my Arch install :/

```
Traceback (most recent call last):
  File "/usr/bin/i3-workspace-groups", line 5, in <module>
    from i3wsgroups.cli import main
ModuleNotFoundError: No module named 'i3wsgroups'
```
