### ISSUE TITLE
 assert local_number < _MAX_WORKSPACES_PER_GROUP TypeError: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by mb720** [infokiller/i3-workspace-groups#25]
Hi!

I'd love to use i3-workspace-groups with Sway 1.2.

Currently, I get an error when calling `i3-rename-workspace`:

    Traceback (most recent call last):
      File "/usr/bin/i3-workspace-groups", line 257, in <module>
        main()
      File "/usr/bin/i3-workspace-groups", line 236, in main
        controller.update_focused_workspace(metadata_updates)
      File "/usr/lib/python3.7/site-packages/i3wsgroups/controller.py", line 304, in update_focused_workspace
        global_name, workspace_id = self._derive_workspace(metadata)
      File "/usr/lib/python3.7/site-packages/i3wsgroups/controller.py", line 234, in _derive_workspace
        return (self._create_workspace_name(metadata), workspace.id)
      File "/usr/lib/python3.7/site-packages/i3wsgroups/controller.py", line 207, in _create_workspace_name
        monitor_index, group_index, (metadata.local_number))
      File "/usr/lib/python3.7/site-packages/i3wsgroups/workspace_names.py", line 232, in compute_global_number
        assert local_number < _MAX_WORKSPACES_PER_GROUP
    TypeError: '<' not supported between instances of 'NoneType' and 'int'

There's a similar stacktrace for `i3-assign-workspace-to-group`:

    Traceback (most recent call last):
      File "/usr/bin/i3-workspace-groups", line 257, in <module>
        main()
      File "/usr/bin/i3-workspace-groups", line 240, in main
        controller.update_focused_workspace(metadata_updates)
      File "/usr/lib/python3.7/site-packages/i3wsgroups/controller.py", line 304, in update_focused_workspace
        global_name, workspace_id = self._derive_workspace(metadata)
      File "/usr/lib/python3.7/site-packages/i3wsgroups/controller.py", line 236, in _derive_workspace
        return (self._create_workspace_name(metadata), None)
      File "/usr/lib/python3.7/site-packages/i3wsgroups/controller.py", line 207, in _create_workspace_name
        monitor_index, group_index, (metadata.local_number))
      File "/usr/lib/python3.7/site-packages/i3wsgroups/workspace_names.py", line 232, in compute_global_number
        assert local_number < _MAX_WORKSPACES_PER_GROUP
    TypeError: '<' not supported between instances of 'NoneType' and 'int'

Am I using this wrong?

Thanks in advance!

---

Python 3.7.4
Arch Linux 5.3.10

**Comment by infokiller** [comment]
Hi!
I'm not using Wayland/Sway myself (though I plan to do it once Wayland matures), so I need your help to debug this.

First, can you verify that you're running the latest version by running `pip install --upgrade i3-workspace-groups` and let me know what version is installed?

Second, please run the following command and post the output: `i3-workspace-groups --log-level debug list-workspaces`

**Comment by infokiller** [comment]
Update: I think I know why this happens and added a commit that may fix this, but it's only in the pre release version for now.
You can install it using `python3 -m pip install --pre --force-reinstall i3-workspace-groups`. Please let me know if it fixes the issue.

**Comment by mb720** [comment]
Yes, this indeed fixes the issue!
Thanks for responding so quickly.

BTW: As I see it, Sway and Wayland are pretty stable. I happily use them for my daily work.
